apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    server: ${CLUSTER_URL}
    certificate-authority-data: ${CA_DATA}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: ml-app  # Default namespace for your application
    user: jenkins-deployer
current-context: default-context
users:
- name: jenkins-deployer
  user:
    token:
