apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-attrition-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-attrition-model
  template:
    metadata:
      labels:
        app: employee-attrition-model
    spec:
      containers:
      - name: employee-attrition-model
        image: siddhesh01/employee-attrition-model:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: model-storage
          mountPath: /app/pickle
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: employee-attrition-service
spec:
  selector:
    app: employee-attrition-model
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employee-attrition-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-attrition-model
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50