apiVersion: v1
kind: Secret
metadata:
  name: ml-app-secrets
  namespace: ml-app
type: Opaque
data:
  # Base64 encoded values
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiOjU0MzIvbWxhcHA=
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTB1XmVzKTE0ZXVheGV1MndkYm9kY21AN21lb3EwJDkwNWctX2c9eSkmejgkay0=