---
- name: Deploy application to Kubernetes
  hosts: k8s_master
  tasks:
    - name: Create application namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ml-app
      become_user: "{{ ansible_user }}"
      
    - name: Copy Kubernetes manifests to master
      copy:
        src: ../kubernetes/
        dest: ~/kubernetes/
        mode: '0644'

    - name: Apply Kubernetes manifests
      command: kubectl apply -f ~/kubernetes/ -n ml-app
      become_user: "{{ ansible_user }}"
      
    - name: Wait for deployments to be ready
      command: kubectl wait --for=condition=Available deployment/backend deployment/frontend -n ml-app --timeout=300s
      become_user: "{{ ansible_user }}"